spring:
  output:
    ansi:
      enabled: always

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost/db_springboot?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  druid:
    initial-size: 3
    min-idle: 3
    max-active: 20
    max-wait: 60000
    filters: stat,wall
    filter:
      stat:
        slow-sql-millis: 3000
        log-slow-sql: true
        merge-sql: true
      wall:
    db-type: mysql

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
    prefix: classpath:/templates/thymeleaf/
    suffix: .html

  mvc:
    static-path-pattern: /static/**

  messages:
    basename: i18n/messages
    encoding: UTF-8

  mail:
    default-encoding: UTF-8
    host: smtp.aliyun.com
    username: user@aliyun.com
    password: password

#  freemarker:
#    template-loader-path: classpath:/templates/
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
#    suffix: .ftl
#    prefix: freemarker/

mybatis:
  type-aliases-package: com.chen.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
    - com.chen.common.BaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql